fix: initial priority causing null pointer exception
目的在修复偶发的
private val _historyItemsMap = mutableMapOf<String, com.android.purebilibili.data.model.response.HistoryItem>()
在 init 时调用 clear 会报错：
java.lang.NullPointerException: Attempt to invoke interface method 'void java.util.Map.clear()' on a null object reference

父类的初始化永远早于子类。当你执行父类的 init 时，子类的成员变量（比如你的 _historyItemsMap）还没有被分配内存空间（处于 uninitialized 状态），此时调用子类方法访问该变量，必然会抛出 NullPointerException。